version: '3'

services:
  product-mysql:
    container_name: product-mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=product_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  api:
    container_name: product-api
    image: product-app-img
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
       - "8080:8080"
    depends_on:
       - product-mysql
    restart: always   

